FF_CONFIGURE="--enable-gpl --enable-version3 --disable-debug"
FF_CFLAGS="-march=tigerlake -mtune=tigerlake -O3 -pipe"
FF_CXXFLAGS="-march=tigerlake -mtune=tigerlake -O3 -pipe"
FF_LDFLAGS=""
GIT_BRANCH="master"
LICENSE_FILE="COPYING.GPLv3"
