FF_CONFIGURE="--enable-version3 --disable-debug"
FF_CFLAGS="-march=znver3 -mtune=znver3 -mprefer-vector-width=256 -O2 -pipe"
FF_CXXFLAGS="-march=znver3 -mtune=znver3 -mprefer-vector-width=256 -O2 -pipe"
FF_LDFLAGS=""
GIT_BRANCH="master"
LICENSE_FILE="COPYING.LGPLv3"
